common/see3cam_cu40.h
common/v4l_camera.h

If I close the camera (delete the object) and reopen it in the same process I get a segfault as soon as I try to read a frame.
I've made two small changes which fix this:
- munmap the v4l buffers in the destructor
- fix an off-by-2 pointer in the see3cam header

fix: segfaults with see3cam

---

imgproc/opencv_unwrap_360.h
imgproc/tests/deserialise/test.cc
imgproc/tests/deserialise_test.yaml
imgproc/tests/serialise/test.cc
imgproc/unwrapconfig_src/unwrapconfig.cc
imgproc/unwrapparams/pixpro_usb.yaml
imgproc/unwrapparams/pixpro_wifi.yaml
imgproc/unwrapparams/see3cam.yaml
imgproc/unwrapparams/webcam360.yaml
video/input.h

In order to support serialising it as part of some larger settings yaml I needed to update the way the ``OpenCVUnwrap360`` class was serialized so it players nicer with the (somewhat gross) OpenCV serialisation system.  However this means you don't seem to be able to serialise objects into the root of a YAML document which meant updating the existing yaml files etc, but now means you can do stuff like this:
```c++
cv::FileStorage settingsFile("experiment_settings.yaml", cv::FileStorage::WRITE);
settingsFile << "localUnwrapper" << m_Unwrapper;
settingsFile << "fov" << m_FOV;
```

Unwrap serialization

---

common/i2c_interface.h

This was required for the I2C code to build (after installing libi2c-dev) on my new Ubuntu 18 install (kernel 4.15ish) - does this work on your various machines (especially arch!)? If it does, don't merge - I need to test on jetsons n'stuff!

extra i2c header required on my ubuntu 18 install

---

camera_recorder/.gitignore
camera_recorder/build.sh
common/i2c_interface.h

I've added an #ifdef which seems to fix the i2c code so it compiles on Ubuntu 16.04 and on my Arch system.

Fix i2c code so it works on new and old kernels

---

ant_world_db_creator/ant_world_db_creator.cc
common/image_database_recorder.h
libantworld/agent.h
video/input.h
video/opengl.h

I've taken the code for writing to the image database (i.e. saving an image and adding a line to the CSV file) and put it in its own header in a generic form.
Now you can do:
```C++
ImageDatabaseRecorder database("database_name", /*followRoute=*/ false);
...
database.saveImage(frame, 0.5_m, 0.5_m, 0_m, 0_deg);
```
The main impetus for this was is so that Norbert can save his image databases from the robot in the same form.

Generic image database header

---

common/flags.mk
examples/lm9ds1/Makefile
projects/stone_cx/.gitignore
projects/stone_cx/MakefileRobot
projects/stone_cx/MakefileRobotDeadReckon
projects/stone_cx/MakefileVicon

This is just for some tiny changes to the build system.
- It turns out you can "opt in" to compiling different unit types. If we disable all except the ones we're using it massively improves build times for bits of code using units.h. If we ever decide we want any other unit types (e.g. acceleration) we can always adjust this.
- I've put the i2c makefile hacks into common/flags.mk, so that they can be used elsewhere. I've updated the robot versions of makefiles in stone_cx to use this, so they now compile for me

Build updates

---

examples/perfect_memory/.gitignore
examples/perfect_memory/Makefile
examples/perfect_memory/perfect_memory_antworld_test.cc
examples/perfect_memory/perfect_memory_test.cc
examples/perfect_memory/plot_ridf.cc
navigation/antworld_rotater.h
navigation/insilico_rotater.h
navigation/perfect_memory.h
navigation/perfect_memory_base.h
navigation/perfect_memory_hog.h
navigation/plot.h
navigation/visual_navigation_base.h

Hi Jamie,
The main change in this PR is that I've added a template argument so one can have an AntAgent rotate on the spot in AntWorld (using OpenGL) as opposed to the usual in-silico image rotation we do. (The tests I've done seem to show that the results aren't massively affected depending on which of these methods we use, but it's good to have the choice.)
I've also made a few, mostly superficial changes to the navigation code but I did also remove the option to save snapshots as one is going along. It made more sense to me to let the user manually save snapshots using the code in image_database.h if desired.
If you're ok with this PR, my next goal was to try to tweak the Ardin/Stone models so they're part of this navigation framework too.

AntWorld rotater + other navigation code updates

---

Doxyfile

At the moment doxygen is generating HTML versions for *all* of our source code files. It seems like unnecessary bloat to have two copies of all the source code in the repo, plus the code in the documentation might be out of date anyway. Shall we drop it? People can always browse the code on Github.

doxygen: Don't include whole source files in documentation

---

navigation/image_database.h
tools/ant_world_db_creator/.gitignore
tools/ant_world_db_creator/ant_world_db_creator.cc
tools/gantry_db_creator/gantry_db_creator.cc
video/input.h
video/opengl.h

Hi Jamie,
I've just been doing some work on the image database code, changing a few things:
1. Recording extra metadata in a ``database_metadata.yaml`` file (database entries are still in a CSV file)
2. Changing to use ``GridRecorder`` and ``RouteRecorder`` classes for writing to image databases
3. Saving grid coordinates in addition to physical positions for grid databases
This is partly for making databases with the gantry (and transferring over old Matlab ones) and it would be useful to have a standardised way of recording the metadata for them, including parameters that we might want to be able to read in (e.g. unwrap parameters used etc.). But I'm hoping that this will also be useful for e.g. the library square data. If you're happy with the format I'll add an example of how to read …

More image database work

---

net/connection.h
os/net.h
robots/norbot.h
robots/surveyor.h
robots/tank.h
robots/tank_netsink.h
video/netsink.h
video/netsource.h

This PR is mostly to fix a silly bug I introduced in my haste to merge the other PR :-/ (I broke reading frames over the network).
I've also added a mechanism for removing network command handlers, mostly for when we're destroying an object and don't want the ``Connection`` to keep trying to call into the destroyed object (which was causing weird segfaults etc. when exiting programs).

Networking fixes

---

examples/perfect_memory/perfect_memory_test.cc
navigation/perfect_memory.h
navigation/perfect_memory_store_hog.h
projects/ardin_mb/mb_memory.cc
projects/ardin_mb/mb_memory.h
projects/ardin_mb/state_handler.cc

I'm planning on trying to finish off my investigations into HOG features and I found a few things were broken when trying to incorporate them into ant world:
- No way of getting parameters to ``PerfectMemoryStore`` - parameters now get forwarded
- Updated interface to ``VisualNavigationBase`` not reflected in ``MBMemory``

Small Ardin MB fixes

---

.gitmodules
libbebop/Makefile
third_party/arsdk3/.gitignore
third_party/arsdk3/Makefile

This PR adds the SDK as a submodule and automatically builds it when building libbebop. It'll only do this if the ``ARSDK_ROOT`` environment variable isn't set though, so we can keep on using it as before. I just thought it might be an idea to bundle it for when other people want to use the Bebop code.

Add Parrot's SDK as git submodule

---

examples/camera_360/camera_360_test.cc
examples/optical_flow/optical_flow_test.cc
examples/perfect_memory/perfect_memory_test.cc
examples/perfect_memory/plot_ridf.cc
examples/see3cam/see3cam_test.cc
libantworld/snapshot_processor_ardin.cc
make_common/bob_robotics.mk
projects/stone_cx/simulator.cc
projects/stone_cx/simulatorReplay.cc
projects/stone_cx/simulatorRobot.cc
tools/unwrapfile/unwrapfile.cc
video/display.h
video/input.h
video/see3cam_cu40.h

So OpenCV 4 is out and Arch has already upgraded, which predictably means that BoB robotics stuff won't compile for me any more.
Thankfully it seems like they haven't introduced any breaking changes that I can tell, but they have removed large chunks of the old C API, which notably means that all the ``CV_*`` constants we're using don't exist any more and you're supposed to use their enums instead (which also exist in OpenCV 3).
I've made these changes and now everything seems to work for me. Hopefully it shouldn't break anything for OpenCV 3 either.

Add support for OpenCV 4

---

common/stopwatch.h
examples/vicon/vicon_plot_test.cc
vicon/udp.h

This adds a ``getElapsedTime()`` method to the ``ObjectData`` class so you can e.g. stop a robot if the positional data is too old.
I've updated one of the examples to show this feature.

Keep track of when Vicon packets were received (fixes #79)

---

README.md

I had to dig into the CMake scripts to find the second option, but these options **should** build OpenCV 4 so it a) generates a pkgconfig file and b) calls it ``opencv.pc`` rather than ``opencv4.pc`` (which breaks our build)

Readme notes about installing with OpenCV 4

---

common/main.h
make_common/bob_robotics.mk
navigation/image_database.h
robots/gantry.h
third_party/path.h
third_party/tinydir.h
tools/gantry_db_creator/.gitignore
tools/gantry_db_creator/gantry_db_creator.cc

It turns out there was a small bug in the example gantry code we have there which I fixed up.
While I was at it I made some other small fixes and added a ``remove_all()`` function to ``path.h`` (after C++17), which uses the tinydir code. Annoyingly Visual Studio also reformatted all the code in ``path.h``.

Fix for gantry code + misc tweaks

---

make_common/bob_robotics.mk
make_common/find_numpy.py

On my laptop, numpy was installed using pip which on Ubuntu 18 means that by default it ends up in ~/.local (which I feel is good). However the mechanism previously used by ``WITH_MATPLOTLIBCPP=1`` fails in this situation (and would also fail if numpy was installed in a virtualenv etc). This change implements the numpy-hunting using Python's own module search which **should** be more robust.

Use python to ensure we're linking against the version of numpy python is actually using

---

examples/perfect_memory/perfect_memory_test.cc
hid/joystick_base.h
hid/joystick_linux.h
hid/joystick_windows.h
navigation/antworld_rotater.h
navigation/infomax.h
navigation/insilico_rotater.h
navigation/perfect_memory.h
navigation/ridf_processors.h

I had to rework various bits of the internal API to make this work, but now you should be able to do:
```
const auto heading = pm.getHeading(image, rotations.begin(), rotations.end());
```
and
```
const auto heading = pm.getHeading(image, 90, 180, 2);
```
etc.
I've done the PR into your branch to make it easier to look at the diff.

Allow for passing pairs of iterators to ``getHeading()`` etc.

---

examples/gazebo_tank/differential_drive_panoramic.world
examples/gazebo_tank/differential_drive_robot/model.sdf
examples/gazebo_tank/gazebo_panoramic_camera.yaml
examples/gazebo_tank/gazebo_tank.cc
examples/gazebo_tank/panoramic_camera/model.config
examples/gazebo_tank/panoramic_camera/model.sdf
examples/gazebo_tank/run.sh
examples/gazebo_tank/simple_camera/model.config
examples/gazebo_tank/simple_camera/model.sdf
include/common/gazebo_node.h
include/video/gazebocamerainput.h

The gazebo_tank example now supports 2 cameras -  the simple camera and a 360-degree camera. The 360-degree camera is intended to simulate the Kodak PixPro SP360, mounted on the top of the robot pointed upwards. The example can be run by executing `./run.sh -p` from the `examples/gazebo_tank` directory. This will also launch a display screen showing the unwrapped panoramic images captured from the 360-degree camera.

Add 360 degree camera to gazebo_tank

---

src/antworld/world.cc

The obj loader loader was uploading colours to the GPU with 32-bit floating point per channel - this is overkill and really hits the fill-rate on low-end cards (results in doubling of frame rate on my not-that low-end card :smile: )
Fixed #148

8-bit vertex colours in LibAntWorld

---

examples/bebop/test_skip

There seems to be some issue with ARSDK on my machine. I'm getting linker warnings that are probably harmless but break Jenkins. I'm thinking we should just disable the Bebop test for the time being so we can merge outstanding PRs.
On that note, would you mind taking a look at #156 when you get a chance? It's fairly small but not particularly urgent.

Hack to fix Jenkins

---

cmake/bob_robotics.cmake

Irritatingly, neither GCC nor Clang produce nice ANSI-coloured output if they detect that output "isn't a terminal - which seems to include whatever pipe-magick cmake includes.
Curtesy of https://medium.com/@alasher/colored-c-compiler-output-with-ninja-clang-gcc-10bfe7f2b949

Restore ANSI colouring of compiler output

---

include/common/timer.h

So, in a lot of my GeNN models, I add ``$(BOB_ROBOTICS_PATH)`` (or, more recently,``$(BOB_ROBOTICS_PATH)/include``) to the include directories in the make files and use a bunch of the header-only stuff in ``genn_utils`` and ``common`` (i.e. timer). However, because of the static initialisation stuff, if ``logging.h`` is included in anything you get linker errors. I'm not sure what the general solution is but my thoughts are:
1. As printing elapsed time is the purpose of the timer rather than some sort of logging information, it should go to ``std::cout`` anyway
2. In header files, "plog/Log.h" rather than "logging.h" should be included.
3. More controversially, aside from in modules with entry points i.e. ``main`` functions, you should include "plog/Log.h" rather than "logging.h" as this …

Stop timer being dependant on logging

---

cmake/bob_robotics.cmake
cmake/external_libs/i2c.cmake
include/robots/norbot.h

This test was implemented backwards in the cmake version (see https://github.com/BrainsOnBoard/bob_robotics/blob/norbot_navigation/common/flags.mk#L94)

CMake I2C fix

---

cmake/bob_robotics.cmake

Gets rid of annoying warnings on my GCC 7

-Wno-deprecated-copy doesn't exist on GCC earlier than 9

---

cmake/bob_robotics.cmake
src/common/path.cc

I think it probably makes more sense to set this at compile time. You do lose the flexibility of being able to change it at runtime, but realistically you're only going to be using one BoB robotics repo for your program at any one time anyway.

Set BoB robotics path at compile time

---

cmake/bob_robotics.cmake
src/robots/bebop/CMakeLists.txt

This is a minor CMake fix for the robots/bebop module.
It seems that on Ubuntu the rpath (to find the ARSDK libs) isn't set correctly, just the runpath (I forget what the proper distinction is), so the ARSDK libs aren't found when running programs using this module. Adding the ``--disable-new-dtags`` flag to the linker for all programs fixes things. I tried just setting it for programs using the robots/bebop module but for some reason this doesn't work.

CMake Bebop fix

---

cmake/bob_robotics.cmake

We don't want colourised output when we're running via Jenkins, partly because the colour escape sequences make the logs less readable, but also because I think it's breaking Jenkins' auto-parsing of error messages.

Don't colourise gcc output on Jenkins

---

resources/antworld/.gitattributes
resources/antworld/seville_vegetation_downsampled.obj

I'm bored of having to keep scping it between my machines and send google drive links to everyone so I think it makes sense to add the (slightly-postprocessed) version of this environment to bob robotics. It's already online at https://insectvision.dlr.de/3d-reconstruction-tools/habitat3d so I can't see why it would be an issue

Turned on LFS and added Seville environment

---

cmake/external_libs/fftw.cmake
cmake/third_party/wavelet2s.cmake
projects/ardin_mb/sandbox/CMakeLists.txt
projects/ardin_mb/sandbox/WaveletSandbox.cpp
third_party/wavelet2s/CMakeLists.txt
third_party/wavelet2s/wavelet2s.cpp
third_party/wavelet2s/wavelet2s.h

I've gone back to building the wavelet lib from source because it's a bit easier and cleaner (plus it'll work on macOS etc. that way). I stuck it in ``third_party/wavelet2s`` and integrated it with the BoB robotics build system. This stuff is on a separate branch in case we ever want to merge it to master separately.
One issue I ran into is that you also need to link against fftw for this library otherwise you get linking errors. This should all just work now.
When you're linking against a library with CMake, you can just supply the name of the library and if it's a system lib *or* CMake is building it too (e.g. it's a subproject added with ``add_subdirectory()``). If not, then you have to give the full path to the library file otherwise your linker won't know where it is.

Fix build for wavelet code

---

.vscode/c_cpp_properties.json
cmake/bob_robotics.cmake
examples/gazebo_display/CMakeLists.txt
examples/gazebo_tank/CMakeLists.txt
examples/gazebo_uav/CMakeLists.txt
include/robots/gazebo/uav_plugin.h

Closes #103.
The newest version of Gazebo requires C++17 and seeing as we were thinking of upgrading to C++17 anyway I thought now might be the time to do it. g++ v7 seems to have good support (https://gcc.gnu.org/projects/cxx-status.html) and that's the default in Ubuntu 18.04 so I think this should be relatively safe to do. Plus it would be handy to have inline variables in a few places instead of nasty macro hacks.

Add support for C++17 and Gazebo v11+

---

include/antworld/world.h
include/genn_utils/connectors.h
projects/ardin_mb/CMakeLists.txt
projects/ardin_mb/ardin_mb.cc
projects/ardin_mb/state_handler.cc
projects/ardin_mb/state_handler.h
src/antworld/renderer.cc

As you witnessed, the version of this project in master wasn't in a state where it could easily be used for anything (apologies @FullAPVayne)! This P.R. fixes the following:
- Adds a CMake option ``NO_GENN`` which doesn't build the GeNN mushroom body and defaults to using the mushroom body
- Fixed outdated SFML key enum
- Fixed incorrect SFML event processing (you couldn't close the window)
- Added a proper CLI using CLI11 to enable you to load different world models and tweak the bits required to make it work with them e.g. loads the new seville ant world model in such a way that it works
``./ardin_mb --world ../../resources/antworld/seville_vegetation_downsampled.obj --height 1.6 --min-bound 0 0 0 --max-bound 10 10 2.8 --clear-colour 0.8 0.8 0.8 1.0``
- Tweaked the way the top-down view …

Ardin MB fixes

---

.vscode/c_cpp_properties.json
cmake/bob_robotics.cmake
src/common/main.cc
src/navigation/image_database.cc

A few times now I've generated image databases with bugs in them and it's often difficult to remember which version of the code you used to generate your data files, so I thought it probably makes sense to write the git commit into the database metadata file. (It probably also makes sense to do this elsewhere for "proper" datasets when we want to be able to repeat the processing that was done reliably.)
I've added separate macros for ``BOB_ROBOTICS_GIT_COMMIT`` and ``BOB_PROJECT_GIT_COMMIT``. The latter is for when you've got a project outside of the BoB robotics tree and want to be able to get at that too.

Provide git hash(es) of project to C++

---

bin/copy_dependencies_vcpkg.bat
cmake/bob_robotics.cmake

So there are two issues with the current strategy of building executables into the bin directory:
1. It's inconsistant with Linux and Mac
2. It breaks GeNN which deposits its dlls into the executable directory to work around the same problem
I've come up with a slightly hacky batch-file based solution which recursively calls [dumpbin](https://docs.microsoft.com/en-us/cpp/build/reference/dumpbin-reference) on the executable to find what dlls it needs and, if they're in VCPKG, copies them to the executable directory if they're newer/not present.

Smarter copying of DLL files

---

include/antworld/route_ardin.h
include/antworld/route_continuous.h
projects/ardin_mb/state_handler.cc
projects/ardin_mb/vector_field.cc
projects/ardin_mb/vector_field.h
src/antworld/renderer.cc
src/antworld/route_ardin.cc
src/antworld/route_continuous.cc
tools/ant_world_db_creator/ant_world_map_creator.cc

I meant to fix this in #185 but totally forgot to. The basic problem was an OpenGL one but there were additional issues with correctly rendering routes and vector fields **above** the ground. This also fixes issues with the ant world map creator and takes advantage of ``Vector2<>`` and ``Pose2<>`` for various bits of route API

Fixed upside-down rendering of top-down view

---

include/common/macros.h
include/navigation/image_database.h
src/antworld/world.cc
src/navigation/image_database.cc
tools/image_database_browser/image_database_browser.cc

Hey!
I've made a couple of small changes to the image database code:
1.  Allow for loading a simple folder of images with ``ImageDatabase``. It just makes it easier to run simulations over image sets without any metadata (e.g. a single route recorded without positional data).
2. Let the user skip to a specific frame with ``image_database_browser`` by typing in a number and pressing g. Handy for when you're analysing image data and what to know what the world looked like at e.g. frame 100 or whatever.
I also tweaked the ``BOB_ASSERT`` macro so it's more like a proper function.
Let me know what you think :smiley:

Image database code updates

---

resources/panoramic_camera_parameters/pixpro_usb.yaml

As pointed out by @tenxlenx, currently we're not cropping anything off the top of the image so unwrapped images look really weird at the top.
Old parameter:
New parameter:

PixPro USB: Set inner radius of unwrap parmas to something sensible

---

cmake/bob_robotics.cmake

Addresses this problem: https://github.com/BrainsOnBoard/bob_robotics/issues/204#issuecomment-720525630
Tested with Ubuntu 16.04 docker image.

CMake v3.5 doesn't have VERSION_GREATER_EQUAL

---

projects/dataset_recorder/data_recorder.cc

This ensures that the data is physically written to disk and not just
lurking in OS memory somewhere. Should make things a bit safer for when we
next get a random power-off.

projects/dataset_recorder: Call sync() before program exit

---

cmake/bob_robotics.cmake
include/navigation/image_database.h
projects/ardin_mb/CMakeLists.txt
projects/dataset_recorder/CMakeLists.txt
projects/norbot_systems_identification/CMakeLists.txt
projects/snapshot_bot/CMakeLists.txt
projects/stone_cx/CMakeLists.txt
projects/uav_navigation/CMakeLists.txt
src/common/main.cc
tools/ant_world_db_creator/CMakeLists.txt

Hi! This idea was (sort of) suggested by @aphilippides a while ago and I thought it might be useful.
Essentially I've just added a few more checks to CMake for code we mark as ``IS_EXPERIMENT=TRUE``, which ideally we'd want to do for any simulation/data collection programs where the data is going to be published somewhere.
Currently the main checks are:
* Whether there are uncommitted changes in the git working tree
* Whether the current git commit is in the master branch
If these checks fail, you get a big red error message whenever you start your program (though otherwise it should run as normal).
This is mostly just to catch the case where e.g. you've accidentally checked out the wrong branch before you run your data collection program.

Extra checks for experiment-grade code

---

include/navigation/image_database.h
projects/ardin_mb/mb_memory.cc
projects/ardin_mb/visual_navigation_ui.cc
projects/norbot_systems_identification/angular_velocity.cc
projects/norbot_systems_identification/speed_test.cc
projects/snapshot_bot/snapshot_bot.cc
projects/stone_cx/robot.cc
projects/stone_cx/simulatorReplay.cc
src/antworld/route_ardin.cc
src/antworld/route_continuous.cc
src/antworld/world.cc
src/navigation/image_database.cc
src/robots/gazebo/uav_plugin.cc
tools/camera_recorder/camera_recorder.cc
tools/obj_process/obj_process.cc

I wanted to fix up the ``ImageDatabase`` code to properly catch IO errors when we're writing databases to disk and thought I'd add the proper error checking to other places where we have ``std::fstream``s.

Set exception masks properly for fstreams

---

cmake/bob_robotics.cmake
cmake/external_libs/openmp.cmake

This should fix the OpenMP issue you were having on the Jetson. I've tested in docker but I suppose we should probably test it on an actual Jetson just to be sure...

Fix OpenMP support for CMake < 3.9

---

.vscode/c_cpp_properties.json
cmake/third_party/development_kit_odk2.cmake
include/video/odk2/odk2.h
src/video/odk2/odk2.cc

I've also fixed a warning about string copying.
There were additional warnings about there being anonymous structs inside the devkit code (which are fine in C), but I guess we can just ignore those for now.

Tweaks for Opteran devkit stuff

---

projects/snapshot_bot/snapshot_bot.cc

One of us fixed this during training but, somehow, this code path slipped through the net (cue much searching through old scripts for the right ``np.loadtxt`` magic to strip off suffixes)

Remove units from VICON data when logging during testing

---

bin/copy_dependencies_vcpkg.bat
cmake/FindTBB.cmake
cmake/bob_robotics.cmake
cmake/external_libs/tbb.cmake
docs_source/requirements.md
examples/infomax/infomax_route_example.cc
include/navigation/infomax.h
include/navigation/insilico_rotater.h
include/navigation/perfect_memory.h
src/navigation/CMakeLists.txt
src/navigation/image_database.cc
src/navigation/visual_navigation_base.cc
tools/snapshot_bot_remote_display/CMakeLists.txt

This is a fairly simple change to use Intel's TBB instead of OpenMP, which should be less of a faff to get working. It may mean that users have to do an ``apt install libtbb-dev`` but it's only a small dependency really.
This does also mean that the parallel navigation code now works on Windows too.

Swap out OpenMP for TBB

---

include/navigation/image_database.h

I can't quite understand why this was occurring - adding brackets doesn't help so I don't think it's some sort of horrible macro operator precedence issue. Maybe a legit compiler bug?

Workaround for compiler error on Visual Studio

---

include/common/background_exception_catcher.h
src/common/background_exception_catcher.cc

As pointed out by @neworderofjamie, std::exception_ptr is not atomic, so we need to protect it from race conditions. Figuring out how to do the correct compare/exchange magic with a std::atomic_bool turned out to be beyond me, so let's just use a mutex.

Protect BackgroundExceptionCatcher::ExceptionPtr with std::mutex

---

include/navigation/insilico_rotater.h

First issue was just that the compiler was too dumb to figure out where ``toIndex`` was. Second one was much gnarlier and probably a compiler bug. It **looked** like the code to initialize thread local variables wasn't being linked correctly and I suspect that this was because the compiler was failing to figure out that the function static thread local variables were actually being used. I made them class static instead and it seemed appeased. Thread local variables still hurt my head a little but I think this is equivalent.

GCC 5.4.0 fixes

---

include/robots/omni2d.h
include/robots/tank.h
src/robots/omni2d.cc
src/robots/tank.cc

This still feels slightly like an example of a bad C++ class hierarchy but I've at least tidied up the network stuff so it should work! As the primary means of selecting a robot seems to be setting ``ROBOT_TYPE``, do we _actually_ want the Robot class hierarchy to be virtual?

Mecanum is tank

---

third_party/matplotlibcpp.h

It seems I was using pointers to data that had been freed via a call to ``Py_DECREF``.

matplotlibcpp: Fix xlim() and ylim()

---

cmake/external_libs/gazebo.cmake

It seems like the only thing it does is force the C++ standard to C++11,
which we don't want.

Don't use GAZEBO_CXX_FLAGS

---

include/navigation/image_database.h
src/navigation/image_database.cc
tools/image_database_to_video/.gitignore
tools/image_database_to_video/CMakeLists.txt
tools/image_database_to_video/image_database_to_video.cc

@tenxlenx currently has a huge number of image databases saved as sequences of images (hundreds of GBs). For the sake of being able to upload them without eating all our Git LFS allowance.
@tenxlenx: I figured rather than uploading the converted databases myself it'd be better to share the tool with you so that you can convert them yourself once you've trimmed all the junk frames etc. (But let's wait until we've merged this PR before running it over the databases.)

Add tool for converting image databases to video format

---

third_party/optional.hpp

std::optional is a rather handy interface that is sadly only available from C++17 onwards.
I'm working on some code where it would make sense to use this kind of interface and I feel like it could be useful elsewhere.

Add std::optional header-only library

---

cmake/bob_robotics.cmake

Fixes #264.
Calling return() in a macro returns from the *parent* scope, which in this case has the effect of aborting BoB_build() before modules etc. have been added, leading to linking errors in the case of projects not in git repos.

Fix building BoB robotics projects that aren't in git repos

---

cmake/external_libs/opencv.cmake

Fixes #265.
Without this, the C++ standard is forced to C++11 on CMake <= v3.10, which causes build errors for BoB robotics code.

Fix builds using OpenCV 4.3+ on CMake <= 3.10

---

examples/perfect_memory/perfect_memory.cc

Commit 530e873b changed the code to use ``Path::getRepoPath()`` to get to the root of the BoB robotics repo, but in doing so accidentally changed the name of the file, breaking the HOG example.

Fix image path in examples/perfect_memory

---

src/common/CMakeLists.txt
src/navigation/CMakeLists.txt
src/robots/control/CMakeLists.txt
tests/CMakeLists.txt

BoB robotics code is currently not building on Ubuntu 16.04 because of an Eigen-related issue. It turns out that the version of Eigen included with Ubuntu 16.04 doesn't create it. Just use the EIGEN3_INCLUDE_DIRS variable instead, which seems to work with both old and new versions of Eigen.
Let me know if this fixes things for you @neworderofjamie !

CMake: Don't use newfangled Eigen3::Eigen target

---

src/common/CMakeLists.txt
src/navigation/CMakeLists.txt
src/robots/control/CMakeLists.txt
tests/CMakeLists.txt

After the big CMake tidy-up, I accidentally removed this, meaning that Eigen was only running single threaded.

CMake: Re-add OpenMP support when building with Eigen

---

Jenkinsfile
bin/download_and_build_genn.sh
src/robots/gazebo/CMakeLists.txt

See issue #295. Let's suppress all clang-tidy warnings for now and deal with it properly in a separate PR.

Temporarily suppress clang-tidy warnings

---

Jenkinsfile
examples/see3cam/see3cam.cc
include/navigation/image_database.h
projects/snapshot_bot/image_input.cc
projects/snapshot_bot/memory.cc
projects/stone_cx/robot.cc
python/antworld/antworld.cc
src/common/main.cc
src/navigation/image_database.cc
src/net/connection.cc
src/os/video.cc
src/robots/tank/net/sink.cc
src/video/input.cc
src/viz/sfml/sfml_world.cc
tools/camera_recorder/camera_recorder.cc

Closes #295.
- Revert "Jenkins: Temporarily disable clang-tidy checks"
- Apply some of clang-tidy's auto-fixes
- Add some missing virtual destructors
- Return initialiser lists in a few places

Fix clang-tidy warnings

---

include/navigation/image_database.h
src/navigation/image_database.cc

Errors looked like this:
```
In file included from [01m[K/home/nvidia/bob_robotics/src/navigation/image_database.cc:5:0[m[K:
[01m[K/home/nvidia/bob_robotics/include/navigation/image_database.h:93:66:[m[K [01;31m[Kerror: [m[Kexpected ‘[01m[K;[m[K’ at end of member declaration
Pose3<millimeter_t, degree_t> pose = Pose3<millimeter_t, degree_t>::nan();
[01;32m[K                                                                  ^[m[K
[01m[K/home/nvidia/bob_robotics/include/navigation/image_database.h:93:66:[m[K [01;31m[Kerror: [m[Kdeclaration of ‘[01m[KBoBRobotics::Pose3<units::unit_t<units::unit<std::ratio<1l, 1000l>, units::unit<std::ratio<1l>, units::base_unit<std::ratio<1l> > >, std::ratio<0l, 1l>, std::ratio<0l, 1l> > >, …
```

Fix: gcc5 didn't like me default-initialising a member variable

---

third_party/units.h

I'm getting a clang-tidy warning from inside units.h and figured this
might fix things. There appear to have been a few small changes made
over the last couple of years (though at the time of writing the last
commit was made two years ago).

Bump units.h lib to new upstream version

---

CMakeLists.txt
bin/build_all_jenkins.sh

This is currently causing tests to fail. The cause seems to be that the Python
module's C++ code won't compile properly via the root CMakeLists.txt file, which
is fine as it can't be built that way anyway (it's only included so that IDEs
can get info about the source files).
So let's just disable building Python C++ code on Jenkins. It's already
build-tested separately anyways.

Fix Jenkins linking errors

---

projects/snapshot_bot/snapshot_bot.cc

This is just a small fix as I spotted a bug in my travels through ``snapshot_bot.cc``.

snapshot_bot: Only add IMU columns to CSV if using IMU

---

projects/snapshot_bot/config.cc
projects/snapshot_bot/config.h
projects/snapshot_bot/image_input.cc
projects/snapshot_bot/image_input.h

This removes some of the boilerplate and replaces the multiple boolean options with a single string one.
This currently won't build on the Mecanum robot as gcc v5 seems not to like the ranges library. My plan is to reflash the Jetson with a newer version of Ubuntu so we can test this change properly.

``snapshot_bot``: Refactor ``ImageInput`` code so it's easier to extend

---

projects/snapshot_bot/CMakeLists.txt
projects/snapshot_bot/config_demo.yaml
projects/snapshot_bot/config_demo_testing.yaml
projects/snapshot_bot/rewrite_config.cc

I've added a program to rewrite snapshot_bot config files to remove old options and put new ones in.
I've mostly just added a few options over the last while *however* note that you now set ``imageInputType`` to a string (e.g., ``raw``, ``histeq``) rather than the old ``shouldUseHistEq``-type boolean options. Make sure you don't get bitten by this! @FullAPVayne @efkag

Add tool to rewrite snapshot_bot config files

---

examples/infomax/infomax_matlab_comparison.cc
examples/infomax/infomax_route_example.cc
include/navigation/infomax.h
projects/snapshot_bot/memory.cc
python/navigation/src/algos.cc
src/navigation/image_database.cc

* Added comments to help future-self
* Now scale weight update by ``N*M`` not just N (pretty sure previously the code actually used ``M``)
* Allow number of hidden units to be specified separately
* Removed unnecessary ``array()`` and ``matrix()`` calls: + and - are always element-wise operations - @alexdewar is there a reason for these I'm not just getting?
* Removed tanh scaling - @amanyazevedoamin tells me it was a detour enroute to discovering the actual problem (updates should scaled as described above)
@amanyazevedoamin  - is there a more sensible default learning rate we should now use?
@alexdewar - after counteracting the learning rate scale, output of ``infomax_matlab_comparison`` is the same as before but differences are non-zero - what's going on here?

Infomax tweaks curtesy of Amany

---

examples/bn055/bn055.cc
include/common/bn055_imu.h
src/common/bn055_imu.cc

These devices startup e.g. if power is lost in configuration mode where they don't read from any axes. I have moved the logic to reset the mode from the BN055 constructor into a method which you can call from your exception handler. If this makes sense, I will incorporate it into the data collection app.

Support resetting of BN055 IMU

---

python/antworld/pyproject.toml
python/navigation/src/algos.cc

I'm afraid I still can't actually get this to work but these two issues definitely didn't help! @alexdewar when I build the old fashioned way e.g.
```
python antworld/setup.py develop
```
from ``python/`` it _appears_ to work but it looks like the egg-link is screwed and Python can't figure out how to map the ``bob_robotics`` python module to the  ``python`` directory and thus the two packages within  (I'm not really sure how the bob_robotics "namespace" thing is supposed to work really - I've never encountered a python package that works like this). The modern way:
```
pip install --editable antworld/
```
Fails with ``ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/its/home/jk421/bob_robotics/python/bob_robotics/antworld'`` which also suggest …

Fixed typo in algos and corrected name of dependency

---

include/antworld/world.h
python/antworld/src/antworld.cc
python/examples/test_antworld.py
src/antworld/world.cc

@thomasMisiek is exploring some exciting new stuff with the rothamsted dataset so I've added a few new features here:
* Exposed the ``cubemapSize``, ``nearClip``, ``farClip``, ``horizontalFOV``, ``verticalFOV`` ``AntWorld::Renderer`` constructor options - useful for higher quality rendering of more complex worlds
* Added fog control to the python wrapper - this is plain OpenGL so need for deeper integration - in a C++ application, you'd just call these directly
* ``agent.set_fog("disabled")`` turns it off
* ``agent.set_fog("linear", start=0, end=1000, "colour": (0.75, 0.75, 0.75))`` turns on the rubbishest form of grey fog
* ``agent.set_fog("exp", density=1.0, "colour": (0.75, 0.75, 0.75))`` turns on a nicer sort of fog  like the screenshot
* ``agent.set_fog("exp2", density=1.0, "colour": …

New options for antworld
