BrainsOnBoard/bob_robotics

- LICENSE
Shall we stick a licence file in here? I went with GPLv2 because that's how GeNN is licensed but we could go with BSD or something if we want a more permissive licence.
> add licence: GPLv2

- imgproc/unwrapconfig_src/unwrapconfig.cc
- os/video.h
- video/panoramic.h
* Removed ``Panoramic`` wrapper - replaced with function
* Tidied a couple of small things
> Small tweaks

- bebop/joystick.cc
- camera_recorder/camera_recorder.cc
- hid/joystick_base.h
- hid/joystick_linux.h
- hid/joystick_windows.h
- robots/tank.h
- stone_cx/simulatorRobot.cc
- stone_cx/simulatorRobotDeadReckon.cc
- stone_cx/simulatorVicon.cc
I've set the default circular deadzone to zero and copied and pasted in the original motor deadzone code into tank.h
> Deadzone fix

- .gitignore
- display_test/Makefile
- display_test/unwrap_display_test.cc
- imgproc/Makefile
- imgproc/tests/Makefile
- imgproc/tests/deserialise/test.cc
- imgproc/tests/serialise/test.cc
- imgproc/unwrapfile_src/unwrapfile.cc
- joystick_test/Makefile
- os/tests/Makefile
- os/tests/list_cameras.cc
- robot_net_test/Makefile
- robots/tank.h
- third_party/path.h
- vicon_test/Makefile
- vicon_test/vicon_blocking_test.cc
- video/input.h
- video/netsink.h
This probably wins least exciting PR ever but hey - it fixes #19 :) This dependency stuff makes Make way less of a horrible build system to work with. The {} syntax you were using in some of the make clean directives didn't seem to work for me so I made it dumber
> Make dependencies

- Jenkinsfile
- ant_world/Makefile
- examples/bebop_test/Makefile
- libbebop/bebop.cc
- video/netsource.h
Having massaged the Jenkins script a little so it actually works, I fixed a few errors it threw up. There's still lots of linker failures on your machine for I2C stuff though and my machine doesn't have the ARSDK installed for all users - I think maybe we need to think carefully about what actually gets automatically tested and what counts as a failure
> Build fixes

- tools/unwrapfile/unwrapfile.cc
As videos are kinda annoying to handle (and because OpenCV seems incapable of writing high quality ones) it seemed useful to have an option to unwrap MP4 files and save some subset of the frames to JPG. Also a bonus bugfix - previous we were assuming in several places that whatever was allocating ``ftype`` vector was zeroing the memory.
> Unwrapping videos to a series of JPGs

- imgproc/opencv_unwrap_360.h
It wasn't compiling properly because units::maths had been injected into its namespace so I fixed it by switching it over to using units
> Switched OpenCV unwrapper to using units

- examples/bebop/bebop_test.cc
- libbebop/bebop.cc
- libbebop/bebop.h
- robots/uav.h
Hi both,
I've made a basic generic UAV class and I've tweaked the Bebop code to inherit from it. It has been build-tested but should probably be tested on the actual drone before merging lest we add some more dents to the wall ;-)
@ajc158 : This is more or less what I had in mind, but I have made some assumptions here: I'm assuming you will want to implement takeOff() and land() functions, but if not we can change this. I've also assumed you want the same joystick controls. There are extra bits that are implemented for the Bebop drone that we could also add to this class if you'll have similar functionality (e.g. obtaining the drone's video stream and getting/setting speed limits). Feel free to branch from this and change things however you like.
> Generic UAV class

- projects/stone_cx/robotCommon.cc
- robots/namespace.h
- robots/norbot.h
- robots/robot.h
- robots/surveyor.h
- robots/tank.h
- robots/tank_netsink.h
- robots/uav.h
I've made a basic generic ``Robot`` class for ``Tank`` and ``UAV`` to inherit from. It provides the functions ``moveForward()``, ``turnOnTheSpot()`` and ``stopMoving()``, with the idea that we can use it for when we want a model to control a robot in a simple way. (We could also have virtual agents with similar functionality, but as it's only applied to robots for now I called it ``Robot``.)
I've also added some ``BOB_ASSERT()``s to check the input parameters for various ``tank()`` functions. The reason I did this instead of clamping the values between -1 and 1 is because I think it would be useful to know when we're giving bad parameters, because it probably means we've done something wrong somewhere!
Whaddya think?
> A very basic generic robot class

- .gitignore
- .vscode/.gitignore
- common/plot_agent.h
- examples/vicon/.gitignore
- examples/vicon/Makefile
- examples/vicon/MakefilePlotTest
- examples/vicon/vicon_plot_test.cc
- hid/joystick_base.h
- hid/joystick_linux.h
- libbebop/bebop.h
- net/socket.h
- robots/norbot.h
- robots/surveyor.h
- robots/tank.h
- third_party/matplotlibcpp.h
Hi Jamie,
The main point of this PR is to fix a small bug I found in the ``Tank::drive()`` function: the value of ``r`` should be divided by ``sqrt(2)``, otherwise we get out-of-range motor values and now with the new ``BOB_ASSERT()``s this breaks things :-)
I've also included some plotting code and a fix for the problem where ``KEY_UP`` and ``KEY_DOWN`` macros were breaking OpenCV as well as some other small bits.
> Minor changes and fixes

- libbebop/bebop.h
- libbebop/video.cc
- video/input.h
- video/netsource.h
- video/opencvinput.h
- video/opengl.h
- video/randominput.h
- video/see3cam_cu40.h
This is a tiny PR that mostly just adds a ``Video::Input`` device that just returns random white noise with a specified image size, for debugging etc. (I was having trouble using my crappy old webcam with OpenCV and adding this was easier!)
I've also included some random misc tidy-ups for ``Video::Input`` classes.
> Random video input device + tidy-ups for Video::Input code

- common/threadable.h
- examples/bebop/bebop_test.cc
- examples/robot_net/computer.cc
- examples/robot_net/computer_proj/RobotNetTestComputer.vcxproj
- examples/robot_net/robot.cc
- examples/robot_net/robot_proj/RobotNetTestRobot.vcxproj
- hid/joystick_base.h
- hid/joystick_linux.h
- libbebop/bebop.cc
- libbebop/bebop.h
- net/node.h
- net/server.h
- os/net.h
- video/display.h
- video/netsink.h
- video/netsource.h
Hi Jamie,
Here's another set of random cleanups and fixes (I really need to start working on one thing, dammit!).
Commit summary:
* Threading tidy-ups and fixes
* Tidy-up and commenting of the cross platform networking code in os/net.h
* Extra minor features for Bebop
* Other minor fixes
> More random updates

- examples/gantry/gantry.cc
- examples/infomax/infomax_route_example.cc
- examples/perfect_memory/perfect_memory_antworld_test.cc
- examples/perfect_memory/perfect_memory_test.cc
- imgproc/opencv_unwrap_360.h
- libantworld/Makefile
- libantworld/agent.h
- libantworld/renderer.h
- libantworld/route_ardin.h
- libantworld/route_continuous.h
- libantworld/world.h
- libbebop/bebop.cc
- libbebop/bebop.h
- navigation/antworld_rotater.h
- navigation/image_database.h
- navigation/infomax.h
- navigation/perfect_memory.h
- navigation/ridf_processors.h
- projects/stone_cx/robotCommon.cc
- projects/stone_cx/simulatorCommon.cc
- projects/stone_cx/simulatorRobot.cc
- robots/gantry.h
- third_party/path.h
- tools/image_database_browser/.gitignore
- tools/image_database_browser/Makefile
- tools/image_database_browser/image_database_browser.cc
- tools/image_database_unwrapper/.gitignore
- tools/image_database_unwrapper/Makefile
- tools/image_database_unwrapper/image_database_unwrapper.cc
- vicon/udp.h
Commit summary:
* Unpollute the namespace from all the ``using namespace units...`` we've been using
* Fix some small compile errors for Stone CX model
* Small fixes for reading image databases' metadata
* Add tools for viewing and unwrapping image databases
> Image database bits, tidying and fixes

- libantworld/route_ardin.cc
- libantworld/route_ardin.h
- libantworld/route_continuous.cc
- libantworld/route_continuous.h
- libantworld/world.cc
- libantworld/world.h
- projects/ardin_mb/state_handler.cc
- tools/ant_world_db_creator/ant_world_db_creator.cc
Hi. This PR just changes libantworld in a few places to throw exceptions when files can't be loaded rather than returning false, in keeping with the style we've used elsewhere.
> Throw exceptions in a few places in libantworld

- examples/vicon/vicon_test.cc
- vicon/udp.h
So I would generally say that using C string functions is a bad idea but, in this case:
1. We really don't want any allocations going on at 100Hz or whatever rate the Vicon is flinging data at us
2. The VICON protocol returns fixed-length strings - I don't see much point in not using them as is.
> Searching for VICON objects by name

- make_common/bob_robotics.mk
- os/video.h
- robots/tank.h
- Improved joystick control by mapping movements outside of deadzone to full range of robot input values
- When projects were compiled and linked separately i.e. with multiple object files, OpenMP wasn't being enabled (at least on ARM64) 
- Some inline functions weren't marked as such
> Small fixes

- examples/pure_pursuit_controller/pure_pursuit_controller_example.cc
- robots/pure_pursuit_controller.h
car now stops if distance to last waypoint < m_stoppingDistance.
getTurningAngle() is now returning a bool indicating if the algorithm could find a valid angle. getLookAheadPoint() is also returning a bool indicating if the algorithm could find a valid lookahead point.
> Pure pursuit controller lastwp

- make_common/bob_robotics.mk
This was broken - I'm guessing this was the intention :smile:
> Include path for imgui not being set

- navigation/infomax.h
- navigation/insilico_rotater.h
* Include ``m_BeginColumn`` in ``columnToHeading`` calculation
* Use ``columnToHeading`` rather than adhocness in ``InfoMaxRotater::getHeading``
> In-silico fixes

- cmake/bob_robotics.cmake
- include/vicon/udp.h
Hi @shinjanxp,
Does this fix the CMake issue you were having? Do the examples build now?
> Possible CMake fix for Ubuntu 16.04

- common/map_coordinate.h
Hey Norbert,
I cherry-picked a couple of small commits off another branch which I thought might be useful to you for the GPS stuff.
Commit summary:
- I made ``GPSCoordinates`` an alias for ``LatLon<WGS84>`` because I thought that would be clearer
- I changed the members of ``LatLon`` non-``const`` (e.g. so that you can assign to a ``LatLon``)
It's using your branch as a base, so just click merge if you're happy with it.
> GPS stuff for Norbert

- libantworld/world.cc
I finally got access to Mike Mangan's LIDAR dataset from Seville and after converting it to obj, had to make some fixes to our obj parser to load them. Namely it was missing support for meshes:
1. Without any texture coordinates or materials
2. Per-vertex colours
> Updated to ``LibAntWorld::World`` for handling more obj file variants

- examples/ant_world/ant_world.cc
- include/hid/joystick_glfw_keyboard.h
- src/hid/CMakeLists.txt
- src/hid/joystick_glfw_keyboard.cc
I have been meaning to do this for a long time (and I know it annoys @tenxlenx regularly) but, sitting here without a joystick was the final straw. This is a GLFW keyboard input based implementation of ``HID::JoystickBase``. I added a wrapper function to ant world that I feel might belong somewhere in ``HID`` but any thoughts would be much appreciated.
> Keyboard joystick

- include/robots/mecanum.h
- include/robots/rc_car_bot.h
- src/robots/mecanum.cc
- src/robots/rc_car_bot.cc
- src/video/rpi_cam.cc
A few things I needed to fix in order to get these modules building on Visual Studio 2019
> Windows fixes

- tools/remote_display/.gitignore
- tools/remote_display/CMakeLists.txt
- tools/remote_display/remote_display.cc
This adds a tool for remotely viewing images produced by a ``Video::NetSource``.
> Remote display tool

- cmake/bob_robotics.cmake
- include/antworld/route_continuous.h
- src/antworld/route_ardin.cc
- src/antworld/route_continuous.cc
- Most important thing is a small fix to ``RouteContinuous`` so you can make repeated calls to ``load``. 
- Added a method to ``RouteContinuous`` to generate Levy walks (based on the wikipedia entry so, if you have any deeper knowledge, it'd be appreciated)
- Fixed a minor windows issue where the wrong library directory was used when making debug builds
Also, in #183, you introduced a fix for the duplicate path-less libraries being added to the Visual Studio project. Adding the library directory fixes this for release but these still need manually removing in debug as, whatever is adding them, doesn't take into account the debugness and adds the versions with the wrong names (which don't exist in the debug library directory). Not sure if that's a helpful clue as to the underlying issue or …
> Mostly routes

- include/imgproc/opencv_unwrap_360.h
- include/navigation/image_database.h
- src/imgproc/opencv_unwrap_360.cc
- src/navigation/image_database.cc
- tools/image_database_unwrapper/image_database_unwrapper.cc
This is just a few minor things. The most notable is that I've parallelised the unwrapping code and other than that it's just some tweaks.
> Tweaks to image database unwrapping

- cmake/bob_robotics.cmake
- src/imgproc/mask.cc
These should be in ``master`` but the first *may* also help your build error....
> Two fixlets

- examples/perfect_memory/perfect_memory.cc
- include/navigation/ridf_processors.h
- src/navigation/image_database.cc
After getting it working, the Visual Studio Debug runtime found a few nasty issues which I've tried to fix here.
> Runtime fixes

- examples/gazebo_tank/gazebo_tank.cc
- examples/gazebo_tank/run.sh
- examples/gazebo_uav/gazebo_uav.cc
- examples/gazebo_uav/run.sh
We could also just use a virtual joystick as a fallback, but in the meantime let's at least get the examples to run without a joystick to make life easier for @nitik1998.
> Allow running Gazebo examples without joystick

- projects/dataset_recorder/CMakeLists.txt
- projects/dataset_recorder/dataset_recorder.cc
@tenxlenx In the end I merged the video recording stuff without the changes to dataset_recorder (#217).
This PR just contains the changes to dataset_recorder and I'll leave it as a placeholder until we've tested the code.
> Save data from dataset_recorder as video files

- .vscode/c_cpp_properties.json
- examples/imgui/imgui.cc
- projects/ardin_mb/ardin_mb.cc
- third_party/imgui/CMakeLists.txt
This fixes a warning we're getting about an out-of-bounds string bug in imgui.
> Bump imgui to v1.83

- bin/download_and_build_genn.sh
- examples/image_database/write_example.cc
- examples/progress_bar/CMakeLists.txt
- examples/progress_bar/progress_bar.cc
- include/common/progress_bar.h
- include/navigation/image_database.h
- include/robots/tank/dummy_tank.h
- projects/dataset_recorder/dataset_recorder.cc
- projects/snapshot_bot/CMakeLists.txt
- projects/snapshot_bot/config.cc
- projects/snapshot_bot/config.h
- projects/snapshot_bot/image_input.cc
- projects/snapshot_bot/memory.cc
- projects/snapshot_bot/memory.h
- projects/snapshot_bot/offline_train.cc
- projects/snapshot_bot/snapshot_bot.cc
- src/common/CMakeLists.txt
- src/common/progress_bar.cc
- src/navigation/image_database.cc
- src/robots/CMakeLists.txt
- tools/ant_world_db_creator/ant_world_db_creator.cc
- tools/gantry_db_creator/gantry_db_creator.cc
This PR implements a few changes suggested by @aphilippides. It's based on #293, so we should merge that first.
The two main changes are:
1. Do training after recording images so we can record at the camera's maximum frame rate (#287)
2. Add option to record databases as video files (useful for larger datasets, #289)
I also ended up refactoring some ``ImageDatabase`` code so the image and video recording classes are now virtual, but no functional change was intended there.
> Snapshot bot enhancements

- include/navigation/image_database.h
- projects/snapshot_bot/CMakeLists.txt
- projects/snapshot_bot/common.cc
- projects/snapshot_bot/common.h
- projects/snapshot_bot/config.cc
- projects/snapshot_bot/config.h
- projects/snapshot_bot/config_demo.yaml
- projects/snapshot_bot/image_input.cc
- projects/snapshot_bot/live_difference.cc
- projects/snapshot_bot/snapshot_bot.cc
- src/navigation/image_database.cc
- third_party/matplotlibcpp.h
Add a couple more config options and a visualisation tool.
> Extra snapshot_bot pieces

- examples/image_database/read_example.cc
- examples/image_database/write_example.cc
- examples/infomax/infomax_route_example.cc
- include/common/pose.h
- include/navigation/image_database.h
- projects/dataset_recorder/dataset_recorder.cc
- projects/snapshot_bot/snapshot_bot.cc
- src/navigation/image_database.cc
- tools/ant_world_db_creator/ant_world_db_creator.cc
- tools/image_database_browser/image_database_browser.cc
Fixes #305.
It makes sense to have the API take a ``Pose3`` as often we do want both position and attitude in 3D. If this information isn't present we can just write NaNs.
> ImageDatabase: Also record pitch and roll

- include/common/serial_interface.h
- include/os/keycodes.h
- src/common/serial_interface.cc
Just a couple of build bugs I found when compiling on @tnowotny's machine.
> MacOS fixes

- projects/snapshot_bot/config.cc
- projects/snapshot_bot/config.h
- projects/snapshot_bot/snapshot_bot.cc
It compiles but I didnt run it on the robot yet.
> added imu data recording to snapshot bot

- include/navigation/image_database.h
- projects/snapshot_bot/snapshot_bot.cc
- python/navigation/bob_robotics/navigation/__init__.py
- python/navigation/src/algos.cc
- python/navigation/src/common.h
- python/navigation/src/database.cc
- python/navigation/src/navigation.cc
- src/navigation/image_database.cc
- tools/ant_world_db_creator/ant_world_db_creator.cc
- tools/gantry_db_creator/gantry_db_creator.cc
- Make helper function for checking for Python signals
- ImageDatabase: If in read mode, ensure the database is not empty
> Add database unwrap support to python module

- include/navigation/image_database.h
- python/navigation/bob_robotics/navigation/__init__.py
- python/navigation/src/database.cc
- src/navigation/image_database.cc
- tools/image_database_to_video/image_database_to_video.cc
This means we can choose to select the CSV files processed by @tnowotny.
> Allow for choosing filename of database entries file

- include/navigation/image_database.h
- src/navigation/image_database.cc
- tools/image_database_unwrapper/image_database_unwrapper.cc
- image_database_unwrapper: Allow for setting output folder name prefix
- Allow for skipping over frames when unwrapping databases
> Minor unwrapper enhancements

- projects/snapshot_bot/config.cc
- projects/snapshot_bot/config.h
- projects/snapshot_bot/image_input.cc
- projects/snapshot_bot/image_input.h
Closes #334.
This gives us another parameter to tweak if the robot's playing up during a demo.
Tagging @efkag @aphilippides
> Add histeq support to snapshot_bot

- projects/snapshot_bot/memory.cc
The snapshot bot encapsulates a bunch of image preprocessing logic in ``ImageInput`` classes. These are **not** thread-safe e.g. ``m_Unwrapped`` at https://github.com/BrainsOnBoard/bob_robotics/blob/snapshot_bot_load_fix/projects/snapshot_bot/image_input.cc#L71 is reused to reduce runtime memory allocations. However, they were being applied during parallelized loading which caused very weird image corruption issues! Making these thread-safe would make this code very messy so I'm just running these serially.
> Parallelism issues in ``MemoryBase::trainRoute`` 
